### ISSUE TITLE
Does this work in the browser or just server side?

### ISSUE THREAD

**Issue by benag** [contra/wifi-location#3]
Why would someone want to geolocate his server?

**Comment by contra** [comment]
@benag You know not all computers are web servers, right? In fact, I'm sending this message to you right now from a contraption known as a "personal computer".

To answer your question: No, because there is no API in the browser for scanning wifi networks which is required to triangulate your location.

**Comment by benag** [comment]
I am just wondering how to use it in an HTML mobile app would React Native helps? it works with Node.js..

**Comment by contra** [comment]
If react native has an API to scan for wifi-networks then yeah, you can use it. I'm sure iOS has a better way of getting the GPS than wifi triangulation though.
